# Solar Eclipses

What is the average duration of total darkness during a total solar eclipse? When did the longest solar eclipse occur?

The file `solar-eclipses.csv` provides information on all solar eclipses from 1901 to 2100, leveraging the ability of scientists to accurately predict the timing and location of future eclipses.

A solar eclipse happens when the Moon moves between the Earth and the Sun, blocking the Sun's light either partially or completely. There are three primary types of solar eclipses:

1. Total Solar Eclipse: The Moon fully covers the Sun, casting a shadow on Earth and revealing the Sun's corona.

2. Partial Solar Eclipse: The Moon obscures only part of the Sun, creating a crescent-shaped appearance.

3. Annular Solar Eclipse: The Moon covers the center of the Sun, leaving a ring-like appearance, known as a "ring of fire," around the edges. This occurs when the Moon is too far from Earth to completely cover the Sun.

The `duration` variable indicates the length of time that the entire moon covers the sun.

In [3]:
import pandas as pd
pd.set_option('display.max_colwidth', 1000)
df = pd.read_csv('../raw/solar-eclipses.csv')
df

,date,eclipse_type,magnitude,duration,region
0,05-18-1901,Total,1.068,06m29s,"s Asia, Australia, e Africa [Total: Indonesia, N Guinea, Madagascar]"
1,11-11-1901,Annular,0.922,11m01s,"ne Africa, Asia, w Europe [Annular: ne Africa, India, Sri Lanka, se Asia]"
2,04-08-1902,Partial,0.064,NaN,northern Canada
3,05-07-1902,Partial,0.859,NaN,"New Zealand, South Pacific"
4,10-31-1902,Partial,0.696,NaN,"c Asia, e Europe"
...,...,...,...,...,...
439,10-24-2098,Partial,0.006,NaN,Southern Ocean (near Antarctica)
440,03-21-2099,Annular,0.932,07m32s,"Australia, N.Z., Antarctica, N. America [Annular: Central Pacific]"
441,09-14-2099,Total,1.068,05m18s,"Americas, Africa [Total: Canada, U.S., Central Atlantic]"
442,03-10-2100,Annular,0.934,07m29s,"Australia, N. America [Annular: Central Pacific, U.S.]"
443,09-04-2100,Total,1.040,03m32s,"Africa, Antarctica [Total: Central Africa, Madagascar]"

### Project Ideas:

- When did the longest solar eclipse occur? The longest total eclipse?
	- Hint: convert duration to seconds. You can use `str.replace('s', '')` to remove the 's' from the duration values.

- What is the average duration of total solar eclipses? 

- Show the next 10 solar eclipses?
	- Hint: convert date to datetime.

In [14]:
longest_eclipse = df.dropna(subset=['duration'])
horas_completo = longest_eclipse['duration'].str.replace('s', '').str.split('m', expand=True)
horas_completo = horas_completo.astype(int)
longest_eclipse[['m', 's']] = horas_completo
longest_eclipse['total_segundos'] = longest_eclipse['m'] * 60 + longest_eclipse['s']
longest_eclipse =longest_eclipse.drop(columns=['m', 's'])
longest_eclipse[['date', 'eclipse_type', 'magnitude', 'duration', 'total_segundos', 'region', ]]

,date,eclipse_type,magnitude,duration,total_segundos,region
0,05-18-1901,Total,1.068,06m29s,389,"s Asia, Australia, e Africa [Total: Indonesia, N Guinea, Madagascar]"
1,11-11-1901,Annular,0.922,11m01s,661,"ne Africa, Asia, w Europe [Annular: ne Africa, India, Sri Lanka, se Asia]"
5,03-29-1903,Annular,0.977,01m53s,113,"e Asia, nw N America [Annular: China, Mongolia, Russia, Canada]"
6,09-21-1903,Total,1.032,02m12s,132,"se Africa, Antarctica, s Australia, N.Z. [Total: Antarctica, s Indian Ocean]"
7,03-17-1904,Annular,0.937,08m07s,487,"e Africa, s Asia[[Annular: Tanzania, Mozambique, Cambodia, Laos, Vietnam, Myanmar]"
...,...,...,...,...,...,...
436,11-04-2097,Annular,0.949,03m36s,216,"Antarctica, Australia [Annular: Antarctica]"
440,03-21-2099,Annular,0.932,07m32s,452,"Australia, N.Z., Antarctica, N. America [Annular: Central Pacific]"
441,09-14-2099,Total,1.068,05m18s,318,"Americas, Africa [Total: Canada, U.S., Central Atlantic]"
442,03-10-2100,Annular,0.934,07m29s,449,"Australia, N. America [Annular: Central Pacific, U.S.]"
443,09-04-2100,Total,1.040,03m32s,212,"Africa, Antarctica [Total: Central Africa, Madagascar]"

In [15]:
average_duration = round(longest_eclipse['total_segundos'].mean() / 60, 2 )

f"{average_duration:.2f} minutos"

'4.02 minutos'

In [16]:
longest_eclipse['date'] = pd.to_datetime(longest_eclipse['date'])
next_10_solar_eclipses = longest_eclipse[longest_eclipse['date'] > pd.Timestamp.now()].head(10)
next_10_solar_eclipses

,date,eclipse_type,magnitude,duration,region,total_segundos
277,2026-08-12,Total,1.039,02m18s,"n N. America, w Africa, Europe [Total: Arctic, Greenland, Iceland, Spain]",138
278,2027-02-06,Annular,0.928,07m51s,"S. America, Antarctica, w & s Africa [Annular: Chile, Argentina, Atlantic]",471
279,2027-08-02,Total,1.079,06m23s,"Africa, Europe, Mid East, w & s Asia [Total:Morocco, Spain, Algeria, Libya, Egypt, Saudi Arabia, Yemen, Somalia]",383
280,2028-01-26,Annular,0.921,10m27s,"e N. America, C. & S. America, w Europe, nw Africa [Annular: Ecuador, Peru, Brazil, Suriname, Spain, Portugal]",627
281,2028-07-22,Total,1.056,05m10s,"SE Asia, E. Indies, Australia, N.Z. [Total: Australia, N. Z.]",310
286,2030-06-01,Annular,0.944,05m21s,"Europe, n Africa, Mid East, Asia, Arctic, Alaska [Annular: Algeria, Tunisia, Greece, Turkey, Russia, n. China, Japan]",321
287,2030-11-25,Total,1.047,03m44s,"s Africa, s Indian Oc., E. Indies, Australia, Antarctica [Total: Botswana, S. Africa, Australia]",224
288,2031-05-21,Annular,0.959,05m26s,"Africa, s Asia, E. Indies, Australia [Annular: Angola, Congo, Zambia, Tanzania, s. India, Malaysia, Indonesia]",326
289,2031-11-14,Hybrid,1.011,01m08s,"Pacific, s US, C. America, nw S. America [Hybrid: Pacific, Panama]",68
290,2032-05-09,Annular,0.996,00m22s,"s S. America, s Africa [Annular: s Atlantic]",22