# Volcano Eruptions

Which volcanoes have experienced the longest eruptions?

The dataset `volcanic-eruptions.csv` includes the start and end dates for all volcanic eruptions since 1800, along with each volcano's identification number. For eruptions that are still ongoing as of December 2024, the end date is recorded as December 2024.

This dataset excludes any eruptive pauses shorter than three months. If an eruption resumes after more than three months of inactivity, it is classified as a new eruption.

Note: Volcano Yasur in Vanuatu is not included in this list due to the absence of a clear start date.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

eruptions = pd.read_csv('../data/volcanic-eruptions.csv')
eruptions.head(3)

   volcano_id start_date end_date
0      211020    07-1913  04-1944
1      211020    02-1864  11-1868
2      211020    12-1854  05-1855

### Additional dataset

The dataset `volcano-list.csv` provides detailed information about each volcano, including its name, country, latitude, longitude, and type.

In [4]:
volcanoes = pd.read_csv('../data/volcano-list.csv')
volcanoes.head(3)

,volcano_id,volcano_name,country,volcanic_region_group,volcanic_region,volcano_landform,primary_volcano_type,activity_evidence,last_known_eruption,latitude,longitude,elevation_m,tectonic_setting,dominant_rock_type
0,210010,West Eifel Volcanic Field,Germany,European Volcanic Regions,Central European Volcanic Province,Cluster,Volcanic field,Eruption Dated,8300 BCE,50.170,6.850,600,Rift zone / Continental crust (>25 km),Foidite
1,210020,Chaine des Puys,France,European Volcanic Regions,Western European Volcanic Province,Cluster,Lava dome(s),Eruption Dated,4040 BCE,45.786,2.981,1464,Rift zone / Continental crust (>25 km),Basalt / Picro-Basalt
2,210030,Olot Volcanic Field,Spain,European Volcanic Regions,Western European Volcanic Province,Cluster,Volcanic field,Evidence Credible,Unknown,42.170,2.530,893,Intraplate / Continental crust (>25 km),Trachybasalt / Tephrite Basanite

### Project Ideas:

- Find the volcanoes that were erupting as of Dec 2024.

- Find the volcanoes that have had the longest volcanic eruptions. 

Hints:
- Use `pd.to_datetime`.

- Merge the volcanoes dataframe into eruptions.

- Before the merge, reduce the dataframes to the columns of interest.

- Use `df.sort_values`.

In [11]:
df_completo = volcanoes.merge(eruptions, on='volcano_id', how='left')
df_completo = df_completo.dropna(subset=['start_date', 'end_date'])

vulcoes = df_completo[['volcano_id', 'volcano_name', 'country', 'start_date', 'end_date']]

In [15]:
eruption_dec_2024 = df_completo.query("start_date >= '2024-12-01' and end_date <= '2024-12-31'")
eruption_dec_2024.head(5)

Empty DataFrame
Columns: [volcano_id, volcano_name, country, volcanic_region_group, volcanic_region, volcano_landform, primary_volcano_type, activity_evidence, last_known_eruption, latitude, longitude, elevation_m, tectonic_setting, dominant_rock_type, start_date, end_date]
Index: []

In [ ]:

volcoes = df_completo.dropna(subset=['start_date', 'end_date'])

volcoes = volcoes

volcoes['start_date'] = pd.to_datetime(volcoes['start_date'],format='%m-%Y')
volcoes['end_date'] = pd.to_datetime(volcoes['end_date'],format='%m-%Y')

volcoes['duration'] = (volcoes['end_date'] - volcoes['start_date'])
volcoes = volcoes.sort_values(by='duration', ascending=False)

volcoes.head(10)

,volcano_id,volcano_name,country,start_date,end_date,duration
3558,342030,Santa Maria,Guatemala,1922-06-01,2024-12-01,37439 days
1836,268010,Dukono,Indonesia,1933-08-01,2024-12-01,33360 days
20,211040,Stromboli,Italy,1934-02-01,2024-12-01,33176 days
4049,352090,Sangay,Ecuador,1934-08-01,2011-03-01,27971 days
3370,332010,Kilauea,United States,1823-02-01,1894-12-01,26236 days
2118,282080,Aira,Japan,1955-10-01,2016-08-01,22220 days
130,221080,Erta Ale,Ethiopia,1967-07-01,2024-12-01,20973 days
4549,390020,Erebus,Antarctica,1972-12-01,2024-12-01,18993 days
271,223030,Nyiragongo,DR Congo,1927-03-01,1977-01-01,18204 days
857,253030,Victory,Papua New Guinea,1890-01-01,1935-01-01,16435 days